# Generated by Django 5.0.1 on 2024-01-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En Attente"),
                            ("EN_COURS", "En Cours"),
                            ("SUSPENDU", "Suspendu"),
                            ("TERMINE", "Terminé"),
                            ("EN_EVAL", "En Évaluation"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_ordre", models.IntegerField()),
                ("description", models.TextField()),
                ("delais", models.DateField()),
                ("checked", models.BooleanField(default=False)),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
