# Generated by Django 5.0.1 on 2024-01-24 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tache",
            old_name="delais",
            new_name="delay",
        ),
        migrations.RenameField(
            model_name="tache",
            old_name="numero_ordre",
            new_name="number_order",
        ),
        migrations.RenameField(
            model_name="tache",
            old_name="projet",
            new_name="project",
        ),
    ]
